"""create users table

Revision ID: dab2dfaff7ca
Revises: 
Create Date: 2026-08-01 10:56:11.243880

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'dab2dfaff7ca'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('item_type', sa.Enum('WORD', 'PHRASE', 'GRAMMAR_RULE', name='knowledgeitemtype'), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=True),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type', 'content', 'cefr_level', name='uq_knowledge_item_identity')
    )
    op.create_index(op.f('ix_knowledge_items_cefr_level'), 'knowledge_items', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_knowledge_items_item_type'), 'knowledge_items', ['item_type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('PASSWORD', 'GOOGLE', 'APPLE', name='authprovider'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_knowledge_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_item_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('repetitions_count', sa.Integer(), nullable=False),
    sa.Column('lapses_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_item_id', name='uq_user_knowledge_state_identity')
    )
    op.create_index(op.f('ix_user_knowledge_states_due_at'), 'user_knowledge_states', ['due_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('current_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('account_level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('is_profile_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_knowledge_states_due_at'), table_name='user_knowledge_states')
    op.drop_table('user_knowledge_states')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_items_item_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_cefr_level'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
